# Generated by Django 4.1.7 on 2023-03-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(default="", max_length=30),
        ),
    ]
