# Generated by Django 4.1.7 on 2023-03-20 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="file_type",
        ),
    ]
