# Generated by Django 4.1.7 on 2023-03-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_remove_book_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="url",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
