# Generated by Django 4.1.7 on 2023-03-24 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_remove_book_file_path_bookupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="file",
            field=models.FileField(default="", upload_to="books/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
